apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: blue-green-check
  namespace: myapp-ns
spec:
  metrics:
    - name: blue-green-page-check
      interval: 10s
      count: 1
      provider:
        job:
          spec:
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                  # Container 1: Web app under test
                  - name: blue-green-app
                    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                    ports:
                      - containerPort: 80

                  # Container 2: Tester
                  - name: tester
                    image: curlimages/curl:8.6.0
                    command: ["/bin/sh", "-c"]
                    args:
                      - |
                        echo "Waiting for webserver..."
                        sleep 5
                        echo "Testing connection to blue-green-app container..."
                        response=$(curl -s -m 10 http://127.0.0.1:80)
                        echo "---- RESPONSE START ----"
                        echo "$response"
                        echo "---- RESPONSE END ----"

                        normalized=$(echo "$response" | tr '[:upper:]' '[:lower:]' | tr -d '\n' | tr -d '\r')

                        if echo "$normalized" | grep -q "blue page"; then
                          echo "OK Blue page detected"
                        elif echo "$normalized" | grep -q "green page"; then
                          echo "OK Green page detected"
                        else
                          echo "FAIL Page not detected"
                          exit 1
                        fi
